pragma Singleton
import QtQml

// Stroke icons of Lucide 1.50.0 on a 24 x 24 grid, drawn with round caps
// and joins and a stroke width of 2. Generated by scripts/gui_assets.py.
//
// Copyright (c) 2026 Lucide Icons and Contributors; ISC License. Some
// icons derive from Feather, copyright (c) 2013-present Cole Bemis; MIT
// License. The license texts are in THIRD_PARTY_NOTICES.txt.
QtObject {
    readonly property string settings: "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915M9 12A3 3 0 1 0 15 12A3 3 0 1 0 9 12Z"
    readonly property string themeSystem: "M12 2v2M14.837 16.385a6 6 0 1 1-7.223-7.222c.624-.147.97.66.715 1.248a4 4 0 0 0 5.26 5.259c.589-.255 1.396.09 1.248.715M16 12a4 4 0 0 0-4-4M19 5l-1.256 1.256M20 12h2"
    readonly property string themeLight: "M8 12A4 4 0 1 0 16 12A4 4 0 1 0 8 12ZM12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"
    readonly property string themeDark: "M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401"
    readonly property string close: "M18 6 6 18M6 6l12 12"
    readonly property string minimize: "M5 12h14"
    readonly property string maximize: "M5 3H19A2 2 0 0 1 21 5V19A2 2 0 0 1 19 21H5A2 2 0 0 1 3 19V5A2 2 0 0 1 5 3Z"
    readonly property string restore: "M10 8H20A2 2 0 0 1 22 10V20A2 2 0 0 1 20 22H10A2 2 0 0 1 8 20V10A2 2 0 0 1 10 8ZM4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"
    readonly property string ping: "M10 2L14 2M12 14L15 11M4 14A8 8 0 1 0 20 14A8 8 0 1 0 4 14Z"
    readonly property string jitter: "M2 13a2 2 0 0 0 2-2V7a2 2 0 0 1 4 0v13a2 2 0 0 0 4 0V4a2 2 0 0 1 4 0v13a2 2 0 0 0 4 0v-4a2 2 0 0 1 2-2"
    readonly property string download: "M12 5v14M19 12l-7 7-7-7"
    readonly property string upload: "M5 12l7-7 7 7M12 19V5"
    readonly property string server: "M4 2H20A2 2 0 0 1 22 4V8A2 2 0 0 1 20 10H4A2 2 0 0 1 2 8V4A2 2 0 0 1 4 2ZM4 14H20A2 2 0 0 1 22 16V20A2 2 0 0 1 20 22H4A2 2 0 0 1 2 20V16A2 2 0 0 1 4 14ZM6 6L6.01 6M6 18L6.01 18"
    readonly property string connection: "M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12ZM12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20M2 12h20"
    readonly property string refresh: "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8M21 3v5h-5M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16M8 16H3v5"
    readonly property string success: "M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12ZM16 9l-5.5 5.5L8 12"
    readonly property string warning: "M21.73 18l-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3M12 9v4M12 17h.01"
    readonly property string error: "M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12ZM15 9l-6 6M9 9l6 6"
    readonly property string info: "M2 12A10 10 0 1 0 22 12A10 10 0 1 0 2 12ZM12 16v-4M12 8h.01"
    readonly property string check: "M20 6 9 17l-5-5"
    readonly property string plus: "M5 12h14M12 5v14"
    readonly property string minus: "M5 12h14"
    readonly property string retry: "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8M3 3v5h5"
    readonly property string play: "M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"
    readonly property string stop: "M5 3H19A2 2 0 0 1 21 5V19A2 2 0 0 1 19 21H5A2 2 0 0 1 3 19V5A2 2 0 0 1 5 3Z"
}
